### ISSUE TITLE
promise is not defined

### ISSUE THREAD

**Issue by jeremyvergnas** [SpoonX/aurelia-autocomplete#19]
Uncaught (in promise) ReferenceError: promise is not defined

Looks like `promise` actually doesn't exist here:
https://github.com/SpoonX/aurelia-autocomplete/blob/master/src/component/autocomplete.js#L246

**Comment by jeremyvergnas** [comment]
@bas080

**Comment by RWOverdijk** [comment]
@jeremyvergnas  Guessing this is old? :)

**Comment by jeremyvergnas** [comment]
@RWOverdijk indeed :)
