### ISSUE TITLE
Placeholder makes i18n required dep

### ISSUE THREAD

**Issue by RWOverdijk** [SpoonX/aurelia-autocomplete#28]
https://github.com/SpoonX/aurelia-autocomplete/blob/8c999077ce82cc7ecec7f9e95ae1beb485765904/dist/amd/component/bootstrap/autocomplete.html#L7

**Comment by JamesReate** [comment]
Had the same issue. Thanks for posting where the problem was, just had to remove the `| translate` and it worked

**Comment by RWOverdijk** [comment]
@JamesReate We do recommend using aurelia-i18n as it's easy to set up and gives your product the flexibility of multiple languages. But yes, this requires a fix.

**Comment by JamesReate** [comment]
Ok, I could do a PR for that. Should the fix be to check if the valueconverter is defined and depending on that do something? Or should it be a property that is set to enable/disable i18n? 
Some of my projects do not need multi-language support, and therefore I would prefer to not bring in unnecessary dependencies. 
Now, on a more conceptual note, given the Single Responsibility Principal (thinking about [SOLID ](https://en.wikipedia.org/wiki/SOLID_(object-oriented_design))best practices), I am not sure if bringing in localization as a required feature of a UI tool is a good idea, ie. this responsibility should lie with the consumer/implementer of the tool.

**Comment by RWOverdijk** [comment]
Oh, I think you misunderstood me. I do **not** want it to be a required dependency, at all. I want it to be entirely optional.

Generally, what we do is use the `t` attribute, as that just doesn't change anything when there is no i18n set up. I'm not sure how we could make this check optional, besides making it configurable and having conditionals.
