### ISSUE TITLE
Problematic type definition for aurelia-autocomple plugin

### ISSUE THREAD

**Issue by Sayan751** [SpoonX/aurelia-autocomplete#36]
Not sure if this a issue or a question. I have already asked this question on [SO](https://stackoverflow.com/questions/46602441/problematic-type-definition-for-aurelia-autocomple-plugin), which is as below. I am posting this here as I have not yet received any answer for the question. If you think this is not a real issue, then please close this one. It would really great if you please provide an answer/work-around either here or in [SO](https://stackoverflow.com/questions/46602441/problematic-type-definition-for-aurelia-autocomple-plugin).

I am trying to use [`aurelia-autocomplete`](https://github.com/SpoonX/aurelia-autocomplete) in my project (based on Webpack), without other aurelia packages from SpoonX. 

Though it works correctly on run time, during build it throws the below error.

> [at-loader] ./node_modules/aurelia-autocomplete/dist/aurelia-autocomplete.d.ts:13:1
    TS1128: Declaration or statement expected.
> [at-loader] ./node_modules/aurelia-autocomplete/dist/aurelia-autocomplete.d.ts:13:16
    TS1005: ';' expected.
> [at-loader] ./node_modules/aurelia-autocomplete/dist/aurelia-autocomplete.d.ts:15:8
    TS1005: ';' expected.
> [at-loader] ./node_modules/aurelia-autocomplete/dist/aurelia-autocomplete.d.ts:17:1
    TS1128: Declaration or statement expected.
> [at-loader] ./node_modules/aurelia-autocomplete/dist/aurelia-autocomplete.d.ts:17:16
    TS1005: ';' expected.
> [at-loader] ./node_modules/aurelia-autocomplete/dist/aurelia-autocomplete.d.ts:13:8
    TS2304: Cannot find name 'declare'.
> [at-loader] ./node_modules/aurelia-autocomplete/dist/aurelia-autocomplete.d.ts:15:3
    TS2304: Cannot find name 'from'.
> [at-loader] ./node_modules/aurelia-autocomplete/dist/aurelia-autocomplete.d.ts:17:8
    TS2304: Cannot find name 'declare'.
> [at-loader] ./node_modules/aurelia-autocomplete/dist/aurelia-autocomplete.d.ts:18:3
    TS2304: Cannot find name 'logger'.

My Visual Studio Code also shows the error in `aurelia-autocomplete.d.ts`.

[![enter image description here][1]][1]

Of course the errors disappear when I comment the problematic exports. Also the notation/syntax for those exports are slightly confusing for me, especially when the `class AutoCompleteCustomElement` is exported below (refer the last line of the screenshot). 

Is there any way around this error?

  [1]: https://i.stack.imgur.com/6sdcl.png

**Comment by RWOverdijk** [comment]
I think this can be solved by using the concat mode in spoonx.js. Could you try that and let me know if it works?

**Comment by Sayan751** [comment]
@RWOverdijk Thank you for comment. However, I am not exactly sure, what you meant. I have checked `node_modules/aurelia-autocomplete/spoonx.js`, where `concat` is set to true already. Can you please clarify it a little bit, or provide link to any documentation? 

BTW, I am using the plugin as follows:

- My `webpack.config`: 
```javascript
...
plugins: [
  new AureliaPlugin(),
  new ModuleDependenciesPlugin({
    "aurelia-autocomplete": [ "./component/autocomplete", "./component/bootstrap/autocomplete.html" ]
  }),
...
```
- My `main.ts`:
```javascript
... 
.plugin(PLATFORM.moduleName("aurelia-autocomplete")); 
...
```

**Comment by RWOverdijk** [comment]
In that case... I'm really not sure about these issues. I don't use typescript myself.

**Comment by kkbrs** [comment]
@Sayan751  have you found a solution, i'm using webpack and i'm also facing the same problem:
Unable to find module with ID: aurelia-autocomplete/component/autocomplete

I have same plugin definition in main.ts and webpack.config as your previous comment.

**Comment by ItWorksOnMyMachine** [comment]
@Sayan751 have you been able to get this plugin to work with webpack?  I can't even get that far.  I have no problem with the build, but at runtime I get an error "Unable to find mudule with ID: aurelia-autocomplete/component/autocomplete.  I have the same plugin config in main.ts and the same ModuleDependenciesPlugin configuration as you do above.

**Comment by Sayan751** [comment]
@kkbrs, @ItWorksOnMyMachine Mentioning you guys as I got email notifications on your comments (but can't see your comments here 😕).

To answer your questions, I have not yet found any solution for this. To make CI, we have simply deleted the type definition file (`aurelia-autocomplete.d.ts`) as a pre-build step. Otherwise the complete build was failing. 
Though this is not an ideal solution 😞 it floats our boat.

**Comment by RWOverdijk** [comment]
I really hope someone puts on their hero pants and solves this some day :)

**Comment by Sayan751** [comment]
@RWOverdijk This issue can be easily resolved in isolation by commenting out (or by removing lines 13-15, and 17-19 in current aurelia-autiocomplete.d.ts ) the below lines:

```javascript
13: // export declare {
14: //   AutoCompleteCustomElement
15: // } from 'aurelia-autocomplete/component/autocomplete';
16: export declare function configure(aurelia?: any, configCallback?: any): any;
17: // export declare {
18: //   logger
19: // };
```
This will certainly make the compiler happy. 

However, I am not sure whether this is aligned with the whole ecosystem of Aurelia componenets from SpoonX.

**Comment by RWOverdijk** [comment]
@Sayan751 The real issue is that this file gets generated automatically. So something is wrong in the source mapping

**Comment by Sayan751** [comment]
@RWOverdijk I have done some digging, and here are my findings.

1. The error with `logger` is easy to solve by directly exporting the `logger` (in `src/aurelia-autocomplete.js`), as can be seen [here](https://github.com/Sayan751/aurelia-autocomplete/commit/d8a8e40955b2e99f93b70bafc7b8a46bf4aa2029#diff-90df266928280c88878521c5aa009a88R24). If you like I can make a PR with this change after doing few more testing.
2. The other error with `AutoCompleteCustomElement` is trickier to solve. Here two things are being done:
    1. `AutoCompleteCustomElement` is being exported from the _root_ of the module `aurelia-autocomplete`. This is causing the generation of erroneous type definition. 
    2. The actual type definition of `AutoCompleteCustomElement` is also concatenated in the type definition file `aurelia-autocomplete.d.ts`. This makes the previous `export` also uneccessary.

Possible solution approaches for the second error:
1. Switch to TypeScript, and generate the type definition files using TypeScript. A viable strategy is to use a separate folder inside `dist` folder for `d.ts` files without concatenating them, and maintaining the `src` folder structure instead. Lastly in order to export the `AutoCompleteCustomElement` from the root of the module `aurelia-autocomplete` a tsindex file generator such as [gulp-create-tsindex](https://github.com/Netatwork-de/gulp-create-tsindex) can be used (disclosure: I am one of the contributor).
2. Raise an issue/question with `babel-dts-generator` to correct the type definition generation.
3. Clean-up such `export`s as a part of build step using `spoonx-tools`.
4. Manually manage the type definition and push it to `@types/`. The type definition is helpful if anyone wants to use the custom element programatically in  TypeScript. Otherwise for a non-complicated case using the element directly from view (`template` html) is enough; and in that case the erroneous type definition is causing more problem than helping.

Hope this helps.

**Comment by Sayan751** [comment]
In case you are planning to use TypeScript, here is [my attempt to migrate to TypeScript](https://github.com/Sayan751/aurelia-autocomplete/tree/TypeScript). Though it is untested, the migration was pretty much straightforward. Please feel free to check it.

**Comment by Sayan751** [comment]
@RWOverdijk 

For the time being I have created a npm package named [aurelia-autocomplete-ts](https://www.npmjs.com/package/aurelia-autocomplete-ts), and I have tested my changes with this package in my project. And it seems to be working for me. Would you be interested in a PR to check if it covers all use-cases or not?

**Comment by RWOverdijk** [comment]
@Sayan751 Does that mean you tested it? I would love a PR. :)

**Comment by Sayan751** [comment]
@RWOverdijk It is working in my project, which may not cover all use-cases. If you want to keep it separate, the PR can be made to a non-master branch.

**Comment by RWOverdijk** [comment]
@Sayan751 Master is fine regardless, I can just make a preversion. Did you fix it without touching the ts file directly?

**Comment by Sayan751** [comment]
The `src` is now in TypeScript. And the type definition (`d.ts`) is being generated from the TypeScript sources using standard procedures (using `gulp-typescript`, here is the `gulpfile`: https://github.com/Sayan751/aurelia-autocomplete/blob/TypeScript/gulpfile.js#L39).

**Comment by RWOverdijk** [comment]
Oh you just rewrote the whole thing, that's neat. It does take away the problem entirely, I like it.

Did you copy the generated code or manually rewrote it?

**Comment by Sayan751** [comment]
It is not strictly a rewrite. I migrated the existing code from JavaScript to TypeScript. The migration process approximately looks like as follows:

1. Add a `tsconfig.json` file containing the common option.
2. Change the source extensions from `.js` to `.ts`.
3. Fix the errors (mainly related to types) reported by tsc.
4. Add a `gulpfile` to have a new build process, which is very much similar to the old one.

and so on...
