### ISSUE TITLE
selected property on keyup or key down isn't set with value

### ISSUE THREAD

**Issue by MECLab-Michelle** [SpoonX/aurelia-autocomplete#42]
Hi there, 

I'm binding a property onto selected and decorating it as observable, but my change event never gets called. I'm thinking that selected isn't being set correctly?

Cheers,

**Comment by RWOverdijk** [comment]
@MECLab-Michelle I'm not sure why it's not being called. selectedChanged should work.

**Comment by RWOverdijk** [comment]
s
