### ISSUE TITLE
minInput is always 0

### ISSUE THREAD

**Issue by Mobe91** [SpoonX/aurelia-autocomplete#43]
I am using version 2.2.3 of aurelia-autocomplete and cannot specify minInput - it constantly evaluates to 0 in `hasEnoughCharacters`. I have tried:
```xml
<auto-complete ... minInput.bind="minInput"></auto-complete>
```
with a corresponding field `minInput` set to 1 in my controller class and
```xml
<auto-complete ... minInput="1"></auto-complete>
```
No idea if this is a bug or if I am doing anything wrong.

**Comment by RWOverdijk** [comment]
Maybe there's no value? Could you make a gist.run or something? This should work.

**Comment by benmess** [comment]
Hi, I seem to have the same problem. I have the autocomplete in a dialog and when it opens I don't want it to show search results. SO I thought I could set the minInput to 2 and then it would show no results until the user typed in at least 2 characters, but this does not seem to work.

<auto-complete minInput="2" items.bind="globalContext.providers" result.bind="item.provInfo"></auto-complete>

Am I doing something wrong? Maybe the results always shows until an item is selected.

**Comment by RWOverdijk** [comment]
It automatically populates some results when opened.

**Update:** I checked the code and don't know how this could happen on subsequent characters. There's a clear character count.

https://github.com/SpoonX/aurelia-autocomplete/blob/master/src/component/autocomplete.js#L288

**Comment by Mobe91** [comment]
Ahhh...
You cannot use camel case attribute names. The following almost works:
```html
<auto-complete ... min-input="1"></auto-complete>
```
However, `minInput` becomes a string in this case and `hasEnoughCharacters` does not consider this. So for now, the workaround ist to use:
```
<auto-complete ... min-input.bind="minInput"></auto-complete>
```
backed by a variable of type `number`.

**Comment by RWOverdijk** [comment]
Ah yes. Or use once with a number inline! :) I feel a bit stupid for not noticing this earlier. Thanks!

**Comment by Mobe91** [comment]
> Or use once with a number inline!

@RWOverdijk Not sure what you mean by that. Could you give an example?

**Comment by RWOverdijk** [comment]
If I'm not mistaken:

value.one-time="${1}"

**Comment by Mobe91** [comment]
Hm good idea but it produces an Aurelia parser error:
```
ERROR [app-router] Error: Parser Error: Missing expected : at column 4 in [${3}]
    at ParserImplementation.error (aurelia-binding.js:3161)
    at ParserImplementation.expect (aurelia-binding.js:3150)
    at ParserImplementation.parseObject (aurelia-binding.js:3114)
    at ParserImplementation.parsePrimary (aurelia-binding.js:3052)
    at ParserImplementation.parseAccessOrCallMember (aurelia-binding.js:2997)
    at ParserImplementation.parsePrefix (aurelia-binding.js:2993)
    at ParserImplementation.parseMultiplicative (aurelia-binding.js:2969)
    at ParserImplementation.parseAdditive (aurelia-binding.js:2955)
    at ParserImplementation.parseRelational (aurelia-binding.js:2937)
    at ParserImplementation.parseEquality (aurelia-binding.js:2919)
```

**Comment by RWOverdijk** [comment]
It should just do a parseInt in the code anyway. If you want, I'd accept a PR for that :)

**Comment by Mobe91** [comment]
🤦‍♂️ 
The correct way to do it is:
```html
<auto-complete ... min-input.one-time="1"></auto-complete>
```
So no PR required actually.
