### ISSUE TITLE
Support for multiple values?

### ISSUE THREAD

**Issue by thomaskonrad** [SpoonX/aurelia-autocomplete#48]
Are there plans to support multiple selected values as Select2 does? Or is that supported already and I missed it?

Thank you
Thomas

**Comment by RWOverdijk** [comment]
@thomaskonrad It is not, no. Or, in a way, it is. I use this in my project with tags. Upon selection I simply clear the autocomplete and add it to the criteria as excluded, so you can't double add values.

A new component could do that, but I think it's too project-specific.

**Comment by RWOverdijk** [comment]
I'm closing this because it's not really an issue, but feel free to respond, I can still provide information.
