### ISSUE TITLE
Bootstrap 4 template?

### ISSUE THREAD

**Issue by graycrow** [SpoonX/aurelia-autocomplete#49]
The current autocomplete.html template is for Bootstrap 3 and doesn't work with Bootstrap 4. Can I override the location of the template, so I can use a different one? I feel that it needs to be done via aurelia-view-manager configuration, but I can not figure out where and how it should be done. I'm using Aurelia-CLI if it's matter.

**Comment by RWOverdijk** [comment]
@graycrow You can also PR bootstrap4. Just copy the current bootstrap dir into bootstrap4 (or something). Then you can configure it using aurelia-config (or straight up configure the view-manager).
