### ISSUE TITLE
Autocomplete is initially uncollapsed when items are supplied

### ISSUE THREAD

**Issue by Mobe91** [SpoonX/aurelia-autocomplete#51]
When an autocomplete is supplied with items and with an initial selection, the items matching the initial selection are uncollapsed after the component is created because `hasFocues` is set to `true` in `valueChanged()`.
```html
<auto-complete result.bind="mySelection" items.bind="myOptions"></auto-complete>
```

**Comment by RWOverdijk** [comment]
I'm sorry, I don't understand this issue. Would you mind giving me a bit more info?

**Comment by Mobe91** [comment]
@RWOverdijk I have created a [sample project](https://github.com/SpoonX/aurelia-autocomplete/files/1859402/aurelia-autocomplete-uncollapsed.zip) that should highlight the issue. When you enter the welcome page you see that the autocomplete is uncollapsed.

Apart from that, the `selected` attribute does not work as stated in the documentation, i.e. it cannot be used to select a default element. Actually, I am not sure what the purpose of this attribute is.
