### ISSUE TITLE
Changes on `result` attribute are not reflected in autocomplete

### ISSUE THREAD

**Issue by Mobe91** [SpoonX/aurelia-autocomplete#53]
When I change the value bound to the autocomplete's `result` attribute from my view controller, the change is not reflected in the view, i.e. the old selection is displayed.

**Comment by RWOverdijk** [comment]
Result is a unidirectional value, fed by the server. If you want to set the value yourself, use selected value instead.

**Comment by Mobe91** [comment]
The `selected` attribute only works for populating an inital selection. Changes to it are not observed by the autocomplete component.

**Comment by Mobe91** [comment]
Apart from that, `result` is declared with a `twoWay` default binding. So either this is misleading or `result` is not meant to be unidirectional.

**Comment by RWOverdijk** [comment]
You're right, it shouldn't be a twoWay binding. You can use a ref and call `.onSelect()`.

**Comment by Mobe91** [comment]
Yeah I already did that as a workaround. But this is not really the Aurelia way, is it? It feels much cleaner to change the view model state and have the component upate itself than to manually invoke methods on the component...

**Comment by RWOverdijk** [comment]
@Mobe91 I agree. If you can find a way that doesn't involve changing the result, I'm all ears. Setting the value is difficult, if you rely on it. You'll end up with circular updates.

Your use case is quite special, what is it needed for?

**Comment by Mobe91** [comment]
The `value` only holds the text content in the input field. Since a user may choose to back the autocomplete with complex objects, I cannot rely on this.
Alternatively I could change the `selected` property to have a `twoWay` binding and try to update the component this way. Would that be acceptable?

My use case is actually not that special. In my application, the user can choose if he wants to save or discard some changes he made. If he chooses to discard I need to reset the autocomplete to its original value in my view model.

**Comment by RWOverdijk** [comment]
Hm I see your point.

We could use `result` then. The only thing to keep in mind, is that the resultChanged method will be called when set from your VM, as well as when selecting an item using the keyboard. This shouldn't cross paths, because after a change like this all cases will call onSelect. This might not be desirable.

If we make this change, it'll be a BC break. Which is fine, we'll just bump a major version. I just think it needs to be a careful change. @jeremyvergnas Feel like jumping in here? I think you use this more than I do.

**Comment by Mobe91** [comment]
@RWOverdijk Regarding your conerns with keyboard selection: I just tried that with my PR and keyboard selection does not seem to be an issue, i.e. `onSelect` is invoked exactly once.

**Comment by RWOverdijk** [comment]
@Mobe91 All right. Seeing how I'm strapped on time, I will give it a last review and release a prerelease.
