### ISSUE TITLE
Unable to find module with ID: aurelia-autocomplete/component/autocomplete

### ISSUE THREAD

**Issue by meta-pratap-ranawat** [SpoonX/aurelia-autocomplete#57]
Hi all,
I started working with aurelia-autocomplete. but i got stuck in initial setting up steps.
versions available at my desk are:
1. node - v8.11.1
2. npm - 5.6.0
3. aurelia - 0.33.1

Steps followed by me to add aurelia-autocomplete plugin
1. au new -> project with typescript and webpack
2. npm install aurelia-autocomplete --save
3. npm install --save
4. adding plugin in main.ts by .plugin(PLATFORM.moduleName('aurelia-autocomplete'))
5. au run --watch
6. browser refresh - No "Hello world!"

on console in browser getting error  - Unhandled rejection Error: Unable to find module with ID: aurelia-autocomplete/component/autocomplete

No error on node terminal

Please help to get started with aurelia-autocomplete

Thanks in advance

**Comment by doktordirk** [comment]
the compoment needs to be added to the webpack.config

like
const { AureliaPlugin, ModuleDependenciesPlugin  } = require('aurelia-webpack-plugin');
...

```
    new AureliaPlugin(),
    new ModuleDependenciesPlugin({
      "aurelia-auttocomplete": [ "./component/autocomplete" ],
    }),
    new ProvidePlugin({
   ```
not sure what to do with the template html though right now. maybe add "./component/bootstrap/autocomplete.html" as well

more info on the ModuleDependenciesPlugin   https://github.com/aurelia/webpack-plugin/wiki/Debugging-missing-modules

**Comment by meta-pratap-ranawat** [comment]
it worked for me.

`new AureliaPlugin(),
new ModuleDependenciesPlugin({
'aurelia-autocomplete': [ './component/autocomplete', './component/bootstrap/autocomplete.html' ],
}),
new ProvidePlugin({`

thanks @doktordirk
