### ISSUE TITLE
Bootstrap 4 support

### ISSUE THREAD

**Issue by Mobe91** [SpoonX/aurelia-autocomplete#58]
I am currently applying some modifications to the component so that it works with bootstrap 4 and I would like to contribute this. How do you want to go about supporting both bs3 and bs4?

**Comment by doktordirk** [comment]
we probably should have versioned the other one. so i guess a bootstrap4 folder.

**Comment by RWOverdijk** [comment]
Yes! That would be amazing.

I'd go for a bootstrap4 folder as well.
