### ISSUE TITLE
Empty populate request

### ISSUE THREAD

**Issue by VMBindraban** [SpoonX/aurelia-autocomplete#59]
https://github.com/SpoonX/aurelia-autocomplete/blob/master/src/component/autocomplete.js#L454

```js
    let query = {
      populate: this.populate || 'null',
      where   : mergedWhere
    };
```

If `populate` is `'null'`, the request will include `populate=null`.
Defaulting it to an empty array will leave out the `populate` property in the request.

**Comment by RWOverdijk** [comment]
This is on purpose, due to how sails handles these requests. If the string null isn't there, it by default populates everything instead of nothing.
