### ISSUE TITLE
Fails to load with webpack

### ISSUE THREAD

**Issue by graywolf336** [SpoonX/aurelia-autocomplete#63]
Hey there, thanks for creating this. I am trying to get it running and I am using the webpack version. I've installed it via npm and have the following in my main file.

`aurelia.use.plugin(PLATFORM.moduleName('aurelia-autocomplete'));`

But then this error happens:
<img width="1006" alt="screen shot 2018-10-15 at 5 22 18 pm" src="https://user-images.githubusercontent.com/850391/46981651-f1816780-d09e-11e8-8fa3-ba8c3131894f.png">

Any ideas or experience?

**Comment by RWOverdijk** [comment]
Did you follow all the steps in the docs?

**Comment by graywolf336** [comment]
As far as I can tell, yes.

**Comment by RWOverdijk** [comment]
It looks like it's missing a module ID. Does the suggestion in this issue help?

https://github.com/SpoonX/aurelia-autocomplete/issues/57

**Comment by graywolf336** [comment]
Good catch, following the directions on #57 does remove the error.
