### ISSUE TITLE
Config and footerSelected help

### ISSUE THREAD

**Issue by chrischain** [SpoonX/aurelia-autocomplete#64]
Hi, I'm relatively new to Aurelia, and I'm working on a project where I'm going to use aurelia-autocomplete.  I've got it (mostly) working, but I could use some help with a couple of things:

Can you provide an example of how to configure the plugin to use the bootstrap4 html file?  I've got the plugin configured in my main.js, but I don't know how to add the option there.

Also, I have been trying to figure out how to watch for changes to the value (which is bound to a child of an object).  I tried to use footerSelected, but I haven't had any success with it.  If you have an example of that, it would be helpful if I could see how to use it.

Thanks!

**Comment by RWOverdijk** [comment]
@chrischain aurelia-autocomplete uses aurelia-view-manager to enable this behaviour.

https://aurelia-view-manager.spoonx.org/defaults.html

As to watching changes I think resultsChanged or valueChanged would do the trick.

**Comment by chrischain** [comment]
Can you post an example of how to use resultsChanged or valueChanged?  I don't seem to be able to get it to work.

**Comment by RWOverdijk** [comment]
@chrischain I'm not really using aurelia at the moment and I don't have time to create examples. If everything still works the way it did you can use the example from the documentation. It's also in the readme. If neither work maybe @jeremyvergnas knows more.
